name: tracer
description: Traces graphs

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  go_router: ^3.0.3
  flutter_svg: ^1.0.3
  email_validator: ^2.0.1
  flutter_reactive_ble: ^5.0.2
  payload:
    git: https://github.com/rvms-capstone/payload.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
